# Generated by Django 6.0.7 on 2026-09-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_fbc_lead_fbp'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='extra_field_values',
            field=models.JSONField(blank=True, default=dict, verbose_name='Respostas de campos personalizados'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
