# Generated by Django 6.0.7 on 2026-07-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Ex: meusite.com.br (sem http:// e sem barra no final)', max_length=255, null=True, unique=True, verbose_name='Domínio próprio'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='domain_verified',
            field=models.BooleanField(default=False, verbose_name='Domínio verificado'),
        ),
    ]
