# Generated by Django 6.0.7 on 2026-07-28 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_tenant_custom_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaConversionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, help_text='Gerado no Business Manager da Meta em Eventos > Configurações > API de Conversões.', max_length=512, verbose_name='Access Token da Conversions API')),
                ('test_event_code', models.CharField(blank=True, help_text='Opcional. Cole o código do painel "Testar eventos" do Meta Events Manager para validar o envio sem misturar com dados reais. Remova depois de testar.', max_length=64, verbose_name='Código de teste de eventos')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_conversion_settings', to='tenants.tenant')),
            ],
        ),
    ]
