http:
  middlewares:
    portainer-auth:
      basicAuth:
        users:
          - "leonadito:$2y$05$jVJxe1suWqyDX7mEgKpkmegCj3n5ryqpvKP0PUU0rBGefq53I/d9q"

  routers:
    portainer-websecure:
      rule: "Host(`portainer.agitare.com.br`)"
      service: portainer
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - portainer-auth
    portainer-web:
      rule: "Host(`portainer.agitare.com.br`)"
      service: portainer
      entryPoints:
        - web
      middlewares:
        - portainer-auth

  services:
    portainer:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9000"
