import io

from django.contrib.auth import get_user_model
from django.core.cache import cache
from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import TestCase
from django.urls import reverse
from django.utils import timezone
from PIL import Image

from leads.models import Lead
from tenants.models import Tenant

from .forms import get_publish_errors
from .models import LandingPage, LandingPageFormField, LandingPageGalleryImage

User = get_user_model()


def make_test_image(name="test.png"):
    buffer = io.BytesIO()
    Image.new("RGB", (10, 10), color="red").save(buffer, format="PNG")
    buffer.seek(0)
    return SimpleUploadedFile(name, buffer.read(), content_type="image/png")


class LandingPageSlugTests(TestCase):
    def setUp(self):
        self.tenant = Tenant.objects.create(name="Diamond Towers", slug="diamond-towers")

    def test_slug_autogenerated_from_title(self):
        page = LandingPage.objects.create(tenant=self.tenant, title="Casas em Tramandaí")
        self.assertEqual(page.slug, "casas-em-tramandai")

    def test_slug_unique_per_tenant_gets_suffix(self):
        LandingPage.objects.create(tenant=self.tenant, title="Casas em Tramandaí")
        second = LandingPage.objects.create(tenant=self.tenant, title="Casas em Tramandaí")
        self.assertEqual(second.slug, "casas-em-tramandai-2")

    def test_same_slug_allowed_across_different_tenants(self):
        other_tenant = Tenant.objects.create(name="Kappel", slug="kappel")
        page1 = LandingPage.objects.create(tenant=self.tenant, title="Lançamento")
        page2 = LandingPage.objects.create(tenant=other_tenant, title="Lançamento")
        self.assertEqual(page1.slug, page2.slug)

    def test_slug_locked_after_publish(self):
        page = LandingPage.objects.create(
            tenant=self.tenant, title="Casas em Tramandaí", published_at=None
        )
        original_slug = page.slug
        page.published_at = timezone.now()
        page.save()
        page.title = "Titulo Totalmente Diferente"
        page.slug = "tentativa-de-mudar"
        page.save()
        page.refresh_from_db()
        self.assertEqual(page.slug, original_slug)


class PublishValidationTests(TestCase):
    def setUp(self):
        self.tenant = Tenant.objects.create(name="Diamond Towers", slug="diamond-towers")

    def test_publish_blocked_without_required_fields_or_gallery(self):
        page = LandingPage.objects.create(tenant=self.tenant, title="Incompleta")
        errors = get_publish_errors(page)
        self.assertTrue(errors)

    def test_publish_allowed_with_required_fields_and_gallery_image(self):
        page = LandingPage.objects.create(
            tenant=self.tenant,
            title="Completa",
            hero_title="Casas em Tramandaí",
            lead_form_heading="Receba informações",
        )
        LandingPageGalleryImage.objects.create(landing_page=page, image=make_test_image())
        errors = get_publish_errors(page)
        self.assertEqual(errors, [])

    def test_publish_blocked_custom_without_lead_form_token(self):
        page = LandingPage.objects.create(
            tenant=self.tenant,
            title="Custom sem token",
            design_variant=LandingPage.CUSTOM,
            custom_html="<html><body>Sem o token aqui</body></html>",
        )
        errors = get_publish_errors(page)
        self.assertTrue(errors)

    def test_publish_blocked_custom_with_empty_html(self):
        page = LandingPage.objects.create(
            tenant=self.tenant, title="Custom vazio", design_variant=LandingPage.CUSTOM
        )
        errors = get_publish_errors(page)
        self.assertTrue(errors)

    def test_publish_allowed_custom_with_lead_form_token_and_no_hero_title(self):
        # Página custom não precisa de hero_title/lead_form_heading/galeria
        # — essas checagens são puladas inteiramente para essa variante.
        page = LandingPage.objects.create(
            tenant=self.tenant,
            title="Custom completo",
            design_variant=LandingPage.CUSTOM,
            custom_html="<html><body>{{LEAD_FORM}}</body></html>",
        )
        errors = get_publish_errors(page)
        self.assertEqual(errors, [])

    def test_publish_blocked_without_contact_method(self):
        page = LandingPage.objects.create(
            tenant=self.tenant,
            title="Sem contato",
            hero_title="Casas em Tramandaí",
            lead_form_heading="Receba informações",
            show_email=False,
            show_phone=False,
        )
        LandingPageGalleryImage.objects.create(landing_page=page, image=make_test_image())
        errors = get_publish_errors(page)
        self.assertTrue(errors)

    def test_publish_allowed_with_phone_only_contact(self):
        page = LandingPage.objects.create(
            tenant=self.tenant,
            title="Só telefone",
            hero_title="Casas em Tramandaí",
            lead_form_heading="Receba informações",
            show_email=False,
            show_phone=True,
            require_phone=True,
        )
        LandingPageGalleryImage.objects.create(landing_page=page, image=make_test_image())
        errors = get_publish_errors(page)
        self.assertEqual(errors, [])


class LandingPageTenantIsolationTests(TestCase):
    def setUp(self):
        self.tenant_a = Tenant.objects.create(name="Tenant A", slug="tenant-a")
        self.tenant_b = Tenant.objects.create(name="Tenant B", slug="tenant-b")
        self.user_a = User.objects.create_user(
            username="usuarioa", email="a@example.com", password="SenhaForte123", tenant=self.tenant_a
        )
        self.user_b = User.objects.create_user(
            username="usuariob", email="b@example.com", password="SenhaForte123", tenant=self.tenant_b
        )
        self.page_b = LandingPage.objects.create(tenant=self.tenant_b, title="Página do B")

    def test_user_a_cannot_view_or_edit_user_b_page(self):
        self.client.force_login(self.user_a)

        edit_response = self.client.get(
            reverse("landingpages:edit", kwargs={"pk": self.page_b.pk})
        )
        self.assertEqual(edit_response.status_code, 404)

        publish_response = self.client.post(
            reverse("landingpages:publish", kwargs={"pk": self.page_b.pk})
        )
        self.assertEqual(publish_response.status_code, 404)

    def test_user_a_cannot_mutate_user_b_form_fields(self):
        self.client.force_login(self.user_a)
        response = self.client.post(
            reverse("landingpages:edit", kwargs={"pk": self.page_b.pk}),
            {
                "form_fields-TOTAL_FORMS": "1",
                "form_fields-INITIAL_FORMS": "0",
                "form_fields-0-field_key": "interesse",
                "form_fields-0-label": "Interesse",
                "form_fields-0-field_type": LandingPageFormField.TEXT,
            },
        )
        self.assertEqual(response.status_code, 404)
        self.assertFalse(
            LandingPageFormField.objects.filter(landing_page=self.page_b).exists()
        )

    def test_list_view_only_shows_own_tenant_pages(self):
        LandingPage.objects.create(tenant=self.tenant_a, title="Página do A")
        self.client.force_login(self.user_a)
        response = self.client.get(reverse("landingpages:list"))
        self.assertContains(response, "Página do A")
        self.assertNotContains(response, "Página do B")


class PublicPageTests(TestCase):
    def setUp(self):
        cache.clear()
        self.tenant = Tenant.objects.create(name="Diamond Towers", slug="diamond-towers")
        self.other_tenant = Tenant.objects.create(name="Other Tenant", slug="other-tenant")
        self.published_page = LandingPage.objects.create(
            tenant=self.tenant,
            title="Casas em Tramandaí",
            status=LandingPage.PUBLISHED,
            hero_title="Casas em Tramandaí",
            lead_form_heading="Receba informações",
        )
        self.draft_page = LandingPage.objects.create(
            tenant=self.tenant, title="Rascunho", status=LandingPage.DRAFT
        )

    def _public_url(self, tenant, page):
        return reverse(
            "public_page", kwargs={"tenant_slug": tenant.slug, "page_slug": page.slug}
        )

    def test_published_page_reachable_via_path_fallback(self):
        response = self.client.get(self._public_url(self.tenant, self.published_page))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Casas em Tramandaí")

    def test_draft_page_404s_publicly(self):
        response = self.client.get(self._public_url(self.tenant, self.draft_page))
        self.assertEqual(response.status_code, 404)

    def test_cross_tenant_slug_spoofing_404s(self):
        # published_page belongs to self.tenant — requesting it through
        # other_tenant's slug must not leak it.
        response = self.client.get(self._public_url(self.other_tenant, self.published_page))
        self.assertEqual(response.status_code, 404)

    def test_utm_params_captured_as_hidden_inputs(self):
        url = self._public_url(self.tenant, self.published_page)
        response = self.client.get(url, {"utm_source": "facebook", "utm_campaign": "teste"})
        self.assertContains(response, 'name="utm_source" value="facebook"')
        self.assertContains(response, 'name="utm_campaign" value="teste"')

    def test_lead_capture_saves_utm_and_creates_lead(self):
        url = self._public_url(self.tenant, self.published_page)
        response = self.client.post(
            url,
            {
                "name": "Maria",
                "email": "maria@example.com",
                "phone": "51999999999",
                "city": "Torres",
                "utm_source": "facebook",
                "website": "",
            },
        )
        self.assertEqual(response.status_code, 200)
        lead = Lead.objects.get(email="maria@example.com")
        self.assertEqual(lead.utm_source, "facebook")
        self.assertEqual(lead.tenant, self.tenant)
        self.assertEqual(lead.landing_page, self.published_page)

    def test_whatsapp_redirect_url_rendered_on_success_when_configured(self):
        self.published_page.whatsapp_redirect_number = "5551999999999"
        self.published_page.whatsapp_redirect_message = "Oi! Quero saber mais."
        self.published_page.save()
        url = self._public_url(self.tenant, self.published_page)
        response = self.client.post(
            url,
            {
                "name": "Maria Silva",
                "email": "maria2@example.com",
                "phone": "51999999999",
                "city": "Torres",
                "website": "",
            },
        )
        self.assertEqual(response.status_code, 200)
        content = response.content.decode("utf-8")
        self.assertIn("wa.me/5551999999999", content)
        self.assertIn("Meu%20nome%20%C3%A9%20Maria", content)

    def test_no_whatsapp_redirect_script_when_not_configured(self):
        url = self._public_url(self.tenant, self.published_page)
        response = self.client.post(
            url,
            {
                "name": "Maria",
                "email": "maria3@example.com",
                "phone": "51999999999",
                "city": "Torres",
                "website": "",
            },
        )
        self.assertNotContains(response, "wa.me/")

    def test_honeypot_filled_does_not_create_lead(self):
        url = self._public_url(self.tenant, self.published_page)
        response = self.client.post(
            url,
            {
                "name": "Bot",
                "email": "bot@example.com",
                "phone": "000",
                "city": "Bot",
                "website": "http://spam.com",
            },
        )
        self.assertEqual(response.status_code, 400)
        self.assertFalse(Lead.objects.filter(email="bot@example.com").exists())

    def test_dynamic_extra_fields_rendered(self):
        LandingPageFormField.objects.create(
            landing_page=self.published_page,
            field_key="interesse",
            label="Interesse",
            field_type=LandingPageFormField.SELECT,
            options_text="Compra\nAluguel",
        )
        response = self.client.get(self._public_url(self.tenant, self.published_page))
        self.assertContains(response, "Interesse")
        self.assertContains(response, "<option")
        self.assertContains(response, "Compra")

    def test_required_custom_field_validation_error(self):
        LandingPageFormField.objects.create(
            landing_page=self.published_page,
            field_key="interesse",
            label="Interesse",
            field_type=LandingPageFormField.SELECT,
            options_text="Compra\nAluguel",
            required=True,
        )
        url = self._public_url(self.tenant, self.published_page)
        response = self.client.post(
            url,
            {
                "name": "Maria",
                "email": "maria@example.com",
                "phone": "51999999999",
                "city": "Torres",
                "website": "",
            },
        )
        self.assertEqual(response.status_code, 400)
        self.assertFalse(Lead.objects.filter(email="maria@example.com").exists())

    def test_extra_field_values_persisted_on_lead(self):
        LandingPageFormField.objects.create(
            landing_page=self.published_page,
            field_key="interesse",
            label="Interesse",
            field_type=LandingPageFormField.SELECT,
            options_text="Compra\nAluguel",
        )
        url = self._public_url(self.tenant, self.published_page)
        response = self.client.post(
            url,
            {
                "name": "Maria",
                "email": "maria@example.com",
                "phone": "51999999999",
                "city": "Torres",
                "website": "",
                "extra_interesse": "Compra",
            },
        )
        self.assertEqual(response.status_code, 200)
        lead = Lead.objects.get(email="maria@example.com")
        self.assertEqual(lead.extra_field_values, {"interesse": "Compra"})

    def test_email_field_hidden_when_show_email_false(self):
        self.published_page.show_email = False
        self.published_page.save()
        response = self.client.get(self._public_url(self.tenant, self.published_page))
        self.assertNotContains(response, 'name="email"')

        url = self._public_url(self.tenant, self.published_page)
        post_response = self.client.post(
            url,
            {
                "name": "Maria",
                "phone": "51999999999",
                "city": "Torres",
                "website": "",
            },
        )
        self.assertEqual(post_response.status_code, 200)
        lead = Lead.objects.get(name="Maria")
        self.assertEqual(lead.email, "")

    def test_phone_label_override_rendered(self):
        self.published_page.phone_label = "WhatsApp"
        self.published_page.save()
        response = self.client.get(self._public_url(self.tenant, self.published_page))
        self.assertContains(response, "WhatsApp")

    def test_custom_variant_renders_custom_html_with_substitutions(self):
        self.published_page.design_variant = LandingPage.CUSTOM
        self.published_page.facebook_pixel_id = "123456789"
        self.published_page.custom_html = (
            "<html><body><h1>Página do cliente</h1>"
            "{{TRACKING_SCRIPTS}}{{LEAD_FORM}}</body></html>"
        )
        self.published_page.save()
        response = self.client.get(self._public_url(self.tenant, self.published_page))
        content = response.content.decode("utf-8")
        self.assertContains(response, "Página do cliente")
        self.assertContains(response, 'id="lead-form-wrapper"')
        self.assertContains(response, "fbq('init', '123456789')")
        self.assertNotIn("{{LEAD_FORM}}", content)
        self.assertNotIn("{{TRACKING_SCRIPTS}}", content)

    def test_custom_variant_does_not_execute_django_template_syntax(self):
        # Regressão anti-SSTI: o conteúdo do tenant precisa voltar verbatim,
        # provando que a substituição é str.replace() literal e não o motor
        # de templates do Django (que executaria {% ... %}/resolveria
        # variáveis de contexto do servidor).
        self.published_page.design_variant = LandingPage.CUSTOM
        self.published_page.custom_html = (
            "<html><body>{{LEAD_FORM}}"
            "<p>{{ settings.SECRET_KEY }}</p>"
            "<p>{% for x in 1 %}malicious{% endfor %}</p>"
            "</body></html>"
        )
        self.published_page.save()
        response = self.client.get(self._public_url(self.tenant, self.published_page))
        content = response.content.decode("utf-8")
        self.assertIn("{{ settings.SECRET_KEY }}", content)
        self.assertIn("{% for x in 1 %}malicious{% endfor %}", content)
