# Generated by Django 6.0.7 on 2026-07-21 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada')], default='draft', max_length=20)),
                ('hero_background_image', models.ImageField(blank=True, null=True, upload_to='landing_pages/hero/')),
                ('hero_background_video_url', models.URLField(blank=True)),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_subtitle', models.CharField(blank=True, max_length=500)),
                ('hero_cta_text', models.CharField(blank=True, default='Receba informações exclusivas', max_length=100)),
                ('hero_cta_target', models.CharField(blank=True, default='lead-form', max_length=100)),
                ('highlight_bar_text', models.CharField(blank=True, max_length=500)),
                ('down_payment_text', models.CharField(blank=True, max_length=255)),
                ('installment_text', models.CharField(blank=True, max_length=255)),
                ('total_value_text', models.CharField(blank=True, max_length=255)),
                ('financing_text', models.CharField(blank=True, max_length=255)),
                ('lead_form_heading', models.CharField(blank=True, default='Receba informações de consultores especializados', max_length=255)),
                ('lead_form_description', models.CharField(blank=True, max_length=500)),
                ('lead_form_button_text', models.CharField(blank=True, default='Obter informações', max_length=100)),
                ('lead_form_button_color', models.CharField(blank=True, default='#2563eb', max_length=20)),
                ('video_section_title', models.CharField(blank=True, max_length=255)),
                ('video_embed_url', models.URLField(blank=True)),
                ('requirements_title', models.CharField(blank=True, default='Requisitos', max_length=255)),
                ('requirements_rich_text', models.TextField(blank=True)),
                ('features_title', models.CharField(blank=True, default='Características do Imóvel', max_length=255)),
                ('features_rich_text', models.TextField(blank=True)),
                ('features_image', models.ImageField(blank=True, null=True, upload_to='landing_pages/features/')),
                ('budget_rich_text', models.TextField(blank=True)),
                ('final_cta_text', models.CharField(blank=True, max_length=100)),
                ('footer_text', models.CharField(blank=True, max_length=255)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50)),
                ('google_ads_id', models.CharField(blank=True, max_length=50)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Criada'), ('updated', 'Atualizada'), ('published', 'Publicada'), ('unpublished', 'Despublicada')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='landingpages.landingpage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landing_pages/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='landingpages.landingpage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='landingpage',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_slug_per_tenant'),
        ),
    ]
