# Generated by Django 6.0.7 on 2026-07-21 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='design_variant',
            field=models.CharField(choices=[('standard', 'Padrão'), ('premium', 'Premium (design autoral, alto padrão)')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_eyebrow',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='location_rich_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='location_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='LandingPageAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='landingpages.landingpage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
