# Generated by Django 6.0.7 on 2026-07-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0002_landingpage_design_variant_landingpage_hero_eyebrow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='budget_rich_text',
            field=models.TextField(blank=True, verbose_name='Texto de orçamento/oportunidade'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='design_variant',
            field=models.CharField(choices=[('standard', 'Padrão'), ('premium', 'Premium (design autoral, alto padrão)')], default='standard', max_length=20, verbose_name='Variante de design'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='down_payment_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Valor de entrada'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID do Facebook Pixel'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='features_image',
            field=models.ImageField(blank=True, null=True, upload_to='landing_pages/features/', verbose_name='Imagem de características'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='features_rich_text',
            field=models.TextField(blank=True, verbose_name='Texto de características'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='features_title',
            field=models.CharField(blank=True, default='Características do Imóvel', max_length=255, verbose_name='Título das características'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='final_cta_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Texto do botão final'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='financing_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Texto sobre financiamento'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='footer_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Texto do rodapé'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='google_ads_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID de conversão do Google Ads'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='landing_pages/hero/', verbose_name='Imagem de fundo do hero'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_background_video_url',
            field=models.URLField(blank=True, verbose_name='URL de vídeo de fundo (opcional)'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_cta_target',
            field=models.CharField(blank=True, default='lead-form', max_length=100, verbose_name='Âncora de destino do botão (ex: lead-form)'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_cta_text',
            field=models.CharField(blank=True, default='Receba informações exclusivas', max_length=100, verbose_name='Texto do botão de ação (CTA)'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_eyebrow',
            field=models.CharField(blank=True, max_length=100, verbose_name='Texto de apoio acima do título'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=500, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título principal (H1)'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='highlight_bar_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='Texto da faixa de destaque'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='installment_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Valor da parcela'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='lead_form_button_color',
            field=models.CharField(blank=True, default='#2563eb', max_length=20, verbose_name='Cor do botão de envio'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='lead_form_button_text',
            field=models.CharField(blank=True, default='Obter informações', max_length=100, verbose_name='Texto do botão de envio'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='lead_form_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Texto de apoio do formulário'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='lead_form_heading',
            field=models.CharField(blank=True, default='Receba informações de consultores especializados', max_length=255, verbose_name='Título do formulário'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='location_rich_text',
            field=models.TextField(blank=True, verbose_name='Texto sobre localização'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='location_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título da seção de localização'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='requirements_rich_text',
            field=models.TextField(blank=True, verbose_name='Texto de requisitos'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='requirements_title',
            field=models.CharField(blank=True, default='Requisitos', max_length=255, verbose_name='Título da seção de requisitos'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título da landing page (interno)'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='total_value_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Valor total'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='video_embed_url',
            field=models.URLField(blank=True, verbose_name='URL de incorporação do vídeo (YouTube/Vimeo embed)'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='video_section_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título da seção de vídeo'),
        ),
        migrations.AlterField(
            model_name='landingpageamenity',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='landingpageamenity',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='landingpageamenity',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='landingpagegalleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Legenda'),
        ),
        migrations.AlterField(
            model_name='landingpagegalleryimage',
            name='image',
            field=models.ImageField(upload_to='landing_pages/gallery/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='landingpagegalleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
