# Generated by Django 6.0.7 on 2026-07-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0003_alter_landingpage_budget_rich_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='financial_conditions_html',
            field=models.TextField(blank=True, verbose_name='Conteúdo HTML personalizado (opcional)'),
        ),
    ]
