# Generated by Django 6.0.7 on 2026-09-04 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0004_landingpage_financial_conditions_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='phone_label',
            field=models.CharField(blank=True, default='Telefone', max_length=50, verbose_name='Rótulo do campo de telefone'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='require_email',
            field=models.BooleanField(default=True, verbose_name='E-mail obrigatório'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='require_phone',
            field=models.BooleanField(default=True, verbose_name='Telefone/WhatsApp obrigatório'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='show_email',
            field=models.BooleanField(default=True, verbose_name='Exibir campo de e-mail'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='show_phone',
            field=models.BooleanField(default=True, verbose_name='Exibir campo de telefone/WhatsApp'),
        ),
        migrations.CreateModel(
            name='LandingPageFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.SlugField(help_text='Usado como chave nas respostas salvas. Ex: interesse, timeline-decisao.', max_length=60, verbose_name='Identificador do campo')),
                ('label', models.CharField(max_length=150, verbose_name='Rótulo exibido')),
                ('field_type', models.CharField(choices=[('text', 'Texto curto'), ('phone', 'Telefone'), ('email', 'E-mail'), ('select', 'Seleção (dropdown)'), ('radio', 'Escolha única (radio)'), ('checkbox', 'Caixa de marcação'), ('textarea', 'Texto longo')], default='text', max_length=20, verbose_name='Tipo de campo')),
                ('required', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('options_text', models.TextField(blank=True, help_text='Usado apenas para Seleção/Escolha única.', verbose_name='Opções (uma por linha)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='landingpages.landingpage')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('landing_page', 'field_key'), name='unique_field_key_per_page')],
            },
        ),
    ]
