# Generated by Django 6.0.7 on 2026-09-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0005_landingpage_phone_label_landingpage_require_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='custom_html',
            field=models.TextField(blank=True, verbose_name='HTML personalizado da página (avançado)'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='design_variant',
            field=models.CharField(choices=[('standard', 'Padrão'), ('premium', 'Premium (design autoral, alto padrão)'), ('custom', 'HTML personalizado (avançado)')], default='standard', max_length=20, verbose_name='Variante de design'),
        ),
    ]
