# Generated by Django 6.0.7 on 2026-09-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0006_landingpage_custom_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='whatsapp_redirect_message',
            field=models.CharField(blank=True, help_text='O primeiro nome do lead é adicionado automaticamente ao final.', max_length=500, verbose_name='Mensagem pré-preenchida do WhatsApp'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='whatsapp_redirect_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número do WhatsApp para redirecionamento (DDI+DDD+número, só dígitos)'),
        ),
    ]
